[project]
name = "stepts-validator"
version = "0.1.0"
description = "STEP file validator using pythonocc-core"
requires-python = ">=3.9"
dependencies = [
    "pythonocc-core>=7.7.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
